# -*- coding: utf-8 -*-
"""Mankala.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jM3Hrt45HPIGPI_BRvouzT-ZfvMq80E
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

import copy
import random
import time
import ipywidgets as widgets
from IPython.display import display, HTML

#Board Indexes and Configuration

P1_PITS = list(range(0, 6))
P1_STORE = 6
P2_PITS = list(range(7, 13))
P2_STORE = 13

class MancalaBoard:
    def __init__(self):
        self.board = [4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 4, 0]
        self.current_player = 1
        self.extra_move_earned = False
        self.stones_captured = 0

    def is_game_over(self):
        p1_empty = all(self.board[i] == 0 for i in P1_PITS)
        p2_empty = all(self.board[i] == 0 for i in P2_PITS)
        return p1_empty or p2_empty

    def clean_up_board(self):
        p1_rem = sum(self.board[i] for i in P1_PITS)
        p2_rem = sum(self.board[i] for i in P2_PITS)
        self.board[P1_STORE] += p1_rem
        self.board[P2_STORE] += p2_rem
        for i in P1_PITS + P2_PITS:
            self.board[i] = 0

    def get_valid_moves(self, player):
        pits = P1_PITS if player == 1 else P2_PITS
        return [i for i in pits if self.board[i] > 0]

    def make_move(self, pit_index):
        stones = self.board[pit_index]
        self.board[pit_index] = 0
        current_idx = pit_index
        player = self.current_player
        self.extra_move_earned = False
        self.stones_captured = 0

        while stones > 0:
            current_idx = (current_idx + 1) % 14
            if player == 1 and current_idx == P2_STORE:
                continue
            if player == 2 and current_idx == P1_STORE:
                continue
            self.board[current_idx] += 1
            stones -= 1

        if player == 1 and current_idx == P1_STORE:
            self.extra_move_earned = True
        elif player == 2 and current_idx == P2_STORE:
            self.extra_move_earned = True

        my_pits = P1_PITS if player == 1 else P2_PITS
        my_store = P1_STORE if player == 1 else P2_STORE

        if current_idx in my_pits and self.board[current_idx] == 1:
            opposite_idx = 12 - current_idx
            if self.board[opposite_idx] > 0:
                captured = self.board[current_idx] + self.board[opposite_idx]
                self.board[my_store] += captured
                self.stones_captured = captured
                self.board[current_idx] = 0
                self.board[opposite_idx] = 0

        if not self.extra_move_earned:
            self.current_player = 2 if player == 1 else 1

        if self.is_game_over():
            self.clean_up_board()

#AI Logic (Minimax Alpha-Beta)
def evaluate_heuristic(board_state, player, heuristic_type, W1=2, W2=1, W3=3, W4=4):
    my_store = board_state.board[P1_STORE] if player == 1 else board_state.board[P2_STORE]
    opp_store = board_state.board[P2_STORE] if player == 1 else board_state.board[P1_STORE]
    my_side_stones = sum(board_state.board[i] for i in (P1_PITS if player == 1 else P2_PITS))
    opp_side_stones = sum(board_state.board[i] for i in (P2_PITS if player == 1 else P1_PITS))
    h1 = my_store - opp_store
    if heuristic_type == 1: return h1
    h2 = W1 * h1 + W2 * (my_side_stones - opp_side_stones)
    if heuristic_type == 2: return h2
    add_move = 1 if board_state.extra_move_earned else 0
    h3 = h2 + W3 * add_move
    if heuristic_type == 3: return h3
    return h3 + W4 * board_state.stones_captured

def minimax_alpha_beta(board_state, depth, alpha, beta, maximizing_player, player, heuristic_type):
    if depth == 0 or board_state.is_game_over():
        return evaluate_heuristic(board_state, player, heuristic_type), None
    valid_moves = board_state.get_valid_moves(board_state.current_player)
    if not valid_moves:
        next_state = copy.deepcopy(board_state)
        next_state.current_player = 2 if next_state.current_player == 1 else 1
        return minimax_alpha_beta(next_state, depth - 1, alpha, beta, not maximizing_player, player, heuristic_type)[0], None
    best_move = random.choice(valid_moves) if valid_moves else None
    if maximizing_player:
        max_eval = float('-inf')
        for move in valid_moves:
            next_state = copy.deepcopy(board_state)
            next_state.make_move(move)
            is_max = maximizing_player if next_state.current_player == board_state.current_player else not maximizing_player
            evaluation, _ = minimax_alpha_beta(next_state, depth - 1, alpha, beta, is_max, player, heuristic_type)
            if evaluation > max_eval:
                max_eval = evaluation
                best_move = move
            alpha = max(alpha, evaluation)
            if beta <= alpha: break
        return max_eval, best_move
    else:
        min_eval = float('inf')
        for move in valid_moves:
            next_state = copy.deepcopy(board_state)
            next_state.make_move(move)
            is_max = maximizing_player if next_state.current_player == board_state.current_player else not maximizing_player
            evaluation, _ = minimax_alpha_beta(next_state, depth - 1, alpha, beta, is_max, player, heuristic_type)
            if evaluation < min_eval:
                min_eval = evaluation
                best_move = move
            beta = min(beta, evaluation)
            if beta <= alpha: break
        return min_eval, best_move


# PREMIUM LIGHT WOODEN STYLE CSS WITH ENHANCED STATUS ROW

custom_css = """
<style>
    .mancala-board {
        background-color: #F5DEB3 !important;
        background-image: linear-gradient(145deg, #F5DEB3, #E6C280) !important;
        border: 6px solid #8B4513 !important;
        border-radius: 25px !important;
        padding: 25px !important;
        box-shadow: 0px 12px 24px rgba(139, 69, 19, 0.3) !important;
    }

    .mancala-pit, .mancala-pit.lm-Widget {
        background-color: #D7CCC8 !important;
        background-image: none !important;
        border: 3px solid #5D4037 !important;
        border-radius: 25px !important;
        font-weight: 900 !important;
        color: #3E2723 !important;
        font-size: 15px !important;
        line-height: 1.3 !important;
        transition: all 0.2s ease-in-out !important;
        box-shadow: inset 0px 5px 8px rgba(0,0,0,0.35) !important;
    }

    .mancala-pit:hover:not(:disabled) {
        background-color: #FFE0B2 !important;
        border-color: #8B4513 !important;
        transform: scale(1.05) !important;
    }

    .mancala-store, .mancala-store.lm-Widget {
        background-color: #CFD8DC !important;
        background-image: none !important;
        border: 4px solid #455A64 !important;
        border-radius: 30px !important;
        font-size: 20px !important;
        font-weight: 900 !important;
        color: #1A237E !important;
        box-shadow: inset 0px 6px 12px rgba(0,0,0,0.4) !important;
    }

    .pit-label-style, .pit-label-style .widget-label {
        color: #3E2723 !important;
        font-weight: 900 !important;
        font-size: 16px !important;
        text-shadow: 1px 1px 1px rgba(255,255,255,0.6) !important;
        text-align: center !important;
    }

    .store-title-style {
        color: #3E2723 !important;
        font-weight: 900 !important;
        font-size: 16px !important;
        text-shadow: 1px 1px 1px rgba(255,255,255,0.6) !important;
        margin-bottom: 6px !important;
    }

    /* Enhanced Larger Status Row Layout */
    .status-text, .status-text .widget-label {
        font-size: 24px !important;
        font-weight: 900 !important;
        color: #3E2723 !important;
        line-height: 1.5 !important;
    }

    .status-container {
        background-color: #FFF8E1 !important;
        padding: 20px 30px !important;
        border-radius: 15px !important;
        border: 3px solid #8B4513 !important;
        border-left: 12px solid #8B4513 !important;
        margin-bottom: 25px !important;
        box-shadow: 0px 6px 15px rgba(0,0,0,0.15) !important;
        width: 100% !important;
        display: flex !important;
        align-items: center !important;
    }
</style>
"""
display(HTML(custom_css))

# Graphical User Interface (GUI)

class MancalaGUI:
    def __init__(self, ai_heuristic=4, ai_depth=4):
        self.game = MancalaBoard()
        self.ai_heuristic = ai_heuristic
        self.ai_depth = ai_depth
        self.output = widgets.Output()

        # Creating a wider wrapper layout for the status bar

        self.status_label = widgets.Label(value="🎮 Game Started! Your Turn (Player 1)")
        self.status_label.add_class("status-text")

        self.status_box = widgets.HBox([self.status_label], layout=widgets.Layout(width='100%'))
        self.status_box.add_class("status-container")

        self.create_board_widgets()
        self.update_gui()

    def get_marbles_text(self, count):
        if count == 0:
            return "Empty"
        elif count <= 4:
            return "🔵" * count + f"\n({count})"
        else:
            return "🔵" * 4 + f"..\n({count})"

    def create_board_widgets(self):
        self.p2_store_btn = widgets.Button(description="", disabled=True, layout=widgets.Layout(width='100px', height='190px'))
        self.p2_store_btn.add_class('mancala-store')

        self.p1_store_btn = widgets.Button(description="", disabled=True, layout=widgets.Layout(width='100px', height='190px'))
        self.p1_store_btn.add_class('mancala-store')

        self.p2_buttons = []
        for idx in reversed(P2_PITS):
            btn = widgets.Button(description="", disabled=True, layout=widgets.Layout(width='85px', height='110px', margin='5px'))
            btn.add_class('mancala-pit')
            self.p2_buttons.append(btn)

        self.p1_buttons = []
        for idx in P1_PITS:
            btn = widgets.Button(description="", layout=widgets.Layout(width='85px', height='110px', margin='5px'))
            btn.add_class('mancala-pit')
            btn.on_click(self.get_click_handler(idx))
            self.p1_buttons.append(btn)

        p2_row = widgets.HBox(self.p2_buttons)
        p1_row = widgets.HBox(self.p1_buttons)

        p2_labels = []
        for i in reversed(P2_PITS):
            lbl = widgets.Label(value=f"Pit {i}", layout=widgets.Layout(width='85px', justify_content='center', margin='0 5px'))
            lbl.add_class('pit-label-style')
            p2_labels.append(lbl)

        p1_labels = []
        for i in P1_PITS:
            lbl = widgets.Label(value=f"Pit {i}", layout=widgets.Layout(width='85px', justify_content='center', margin='0 5px'))
            lbl.add_class('pit-label-style')
            p1_labels.append(lbl)

        p2_labels_hbox = widgets.HBox(p2_labels)
        p1_labels_hbox = widgets.HBox(p1_labels)

        middle_pits = widgets.VBox([p2_labels_hbox, p2_row, p1_row, p1_labels_hbox], layout=widgets.Layout(align_items='center'))

        ai_store_lbl = widgets.Label(value="🟡 AI Store")
        ai_store_lbl.add_class('store-title-style')

        your_store_lbl = widgets.Label(value="🔵 Your Store")
        your_store_lbl.add_class('store-title-style')

        self.board_layout = widgets.HBox([
            widgets.VBox([ai_store_lbl, self.p2_store_btn], layout=widgets.Layout(align_items='center')),
            middle_pits,
            widgets.VBox([your_store_lbl, self.p1_store_btn], layout=widgets.Layout(align_items='center'))
        ], layout=widgets.Layout(align_items='center', justify_content='center'))
        self.board_layout.add_class('mancala-board')

    def update_gui(self):
        self.p2_store_btn.description = f"🟡 x {self.game.board[13]}" if self.game.board[13] > 0 else "0"
        self.p1_store_btn.description = f"🔵 x {self.game.board[6]}" if self.game.board[6] > 0 else "0"

        for i, idx in enumerate(reversed(P2_PITS)):
            count = self.game.board[idx]
            self.p2_buttons[i].description = "🟡" * count + f"\n({count})" if count <= 4 else "🟡" * 4 + f"..\n({count})" if count > 0 else "Empty"

        valid_moves = self.game.get_valid_moves(1)
        for i, idx in enumerate(P1_PITS):
            count = self.game.board[idx]
            self.p1_buttons[i].description = "🔵" * count + f"\n({count})" if count <= 4 else "🔵" * 4 + f"..\n({count})" if count > 0 else "Empty"

            if self.game.is_game_over() or self.game.current_player != 1 or idx not in valid_moves:
                self.p1_buttons[i].disabled = True
            else:
                self.p1_buttons[i].disabled = False

    def get_click_handler(self, pit_idx):
        def on_button_clicked(b):
            if self.game.current_player == 1 and not self.game.is_game_over():
                self.game.make_move(pit_idx)
                self.update_gui()

                if self.game.is_game_over():
                    self.check_winner()
                    return

                if self.game.current_player == 1:
                    self.status_label.value = "🎉 Extra Move! You earned another turn."
                else:
                    self.status_label.value = "🤖 AI is thinking..."
                    self.ai_turn()
        return on_button_clicked

    def ai_turn(self):
        while self.game.current_player == 2 and not self.game.is_game_over():
            time.sleep(0.8)
            _, move = minimax_alpha_beta(self.game, self.ai_depth, float('-inf'), float('+inf'), True, 2, self.ai_heuristic)
            if move is not None:
                self.game.make_move(move)
                self.update_gui()
                if self.game.extra_move_earned and not self.game.is_game_over():
                    self.status_label.value = f"🤖 AI chose Pit {move} and earned an Extra Move!"
                else:
                    self.status_label.value = f"🤖 AI chose Pit {move}. Now it's your turn!"
            else:
                break
        if self.game.is_game_over():
            self.check_winner()

    def check_winner(self):
        self.update_gui()
        p1_score = self.game.board[P1_STORE]
        p2_score = self.game.board[P2_STORE]
        result_text = f"🏆 Game Over! Your Score: {p1_score} | AI Score: {p2_score}. "
        if p1_score > p2_score: result_text += "🎉 You Win!"
        elif p2_score > p1_score: result_text += "🤖 AI Wins!"
        else: result_text += "🤝 It's a Tie!"
        self.status_label.value = result_text

    def display(self):
        with self.output:
            display(widgets.VBox([self.status_box, widgets.Label(value=""), self.board_layout]))
        display(self.output)

#Start the Game
gui = MancalaGUI(ai_heuristic=4, ai_depth=4)
gui.display()